
ansible_link_config:
  host: '127.0.0.1'
  port: 5001
  debug: false
  suppress_ansible_output: false
  omit_event_data: false
  only_failed_event_data: false
  metrics_port: 9091  
  playbook_dir: '/etc/ansible/playbooks'
  inventory_file: '/etc/ansible/hosts'
  job_storage_dir: '/tmp/ansible-link-jobs'
  log_level: 'INFO'
  playbook_whitelist: []
  # Optional webhook configuration
  webhook:
    url: ""
    type: ""
  #   timeout: 5
  
ansible_link__deploy_dir: /mnt/data/ansible_link
ansible_link__deploy_group: root
ansible_link__deploy_user: root

ansible_link__image: python:3.9-slim

ansible_link__label: false

ansible_link__network: public

ansible_link__nfs: false
ansible_link__nfs_ip: 0.0.0.0
ansible_link__nfs_dir: "/mnt/nfs/ansible_link"

ansible_link__state: started

ansible_link__version: latest

ansible_link__webhook: false
ansible_link__webhook_type: ""
ansible_link__webhook_url: ""

traefik: true
