
ansible_link__deploy_dir: /mnt/data/ansible_link
ansible_link__deploy_group: root
ansible_link__deploy_user: root

ansible_link__image: python:3.9-slim

ansible_link__label: false

ansible_link__network: public

ansible_link__nfs: false
ansible_link__nfs_ip: 0.0.0.0
ansible_link__nfs_dir: "/mnt/nfs/ansible_link"

ansible_link__state: started

ansible_link__version: latest

traefik: true
